# Generated by Django 4.0.1 on 2022-01-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='img',
            new_name='image',
        ),
    ]
