# Generated by Django 4.0.1 on 2022-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
