# Generated by Django 4.0.1 on 2022-01-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_imagemodel_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='processed',
            field=models.BooleanField(),
        ),
    ]
