# Generated by Django 4.0.1 on 2022-01-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_imagemodel_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='message',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
